version: "3.9"
services:
  mqtt:
    image: eclipse-mosquitto:2.0.15
    network_mode: "host"
    ports:
      - 1884:1884
    volumes:
      - ./env-config/mosquitto:/mosquitto/config
    healthcheck:
      test: ["CMD-SHELL", mosquitto_sub -p 1884 -t 'topic' -C 1 -E -i probe -W 3]
      interval: 5s
      retries: 3
      start_period: 1s
      timeout: 10s   
      
  aas-env:
    image: eclipsebasyx/aas-environment:2.0.0-SNAPSHOT
    network_mode: "host"
    volumes:
      - ./env-config/aas-env.properties:/application/application.properties
      - ./env-config/aas:/application/aas
    ports:
        - 8081:8081
    depends_on:
        mqtt:
          condition: service_healthy
        aas-registry:
          condition: service_healthy
        sm-registry:
          condition: service_healthy

  aas-registry:
    image: eclipsebasyx/aas-registry-log-mem:2.0.0-SNAPSHOT
    network_mode: "host"
    ports:
      - '9081:9081'
    environment:
      - SERVER_PORT=9081
    volumes:
      - ./env-config/aas-registry.yml:/workspace/config/application.yml

  sm-registry:
    image: eclipsebasyx/submodel-registry-log-mem:2.0.0-SNAPSHOT
    network_mode: "host"
    ports:
      - '9082:9082'
    environment:
      - SERVER_PORT=9082
    volumes:
      - ./env-config/sm-registry.yml:/workspace/config/application.yml