version: "3.9"
include:
  - docker-compose-camunda.yml
services:
  mqtt:
    image: eclipse-mosquitto:2.0.15
    ports:
      - 1884:1884
    volumes:
      - ./config/mosquitto:/mosquitto/config
    healthcheck:
      test: ["CMD", "mosquitto_sub", "-p", "1884", "-t", "$$SYS/#", "-C", "1", "-i", "healthcheck", "-W", "3"]
      interval: 5s
      retries: 3
      start_period: 1s
      timeout: 10s 

  aas-env:
    image: eclipsebasyx/aas-environment:2.0.0-SNAPSHOT
    volumes:
      - ./config/aas-env.properties:/application/application.properties
      - ./config/aas:/application/aas
    ports:
        - 8091:8081
    depends_on:
        mqtt:
          condition: service_healthy
        aas-registry:
          condition: service_healthy
        sm-registry:
          condition: service_healthy

  aas-registry:
    image: eclipsebasyx/aas-registry-log-mem:2.0.0-SNAPSHOT
    ports:
      - '9081:9081'
    environment:
      - SERVER_PORT=9081
    volumes:
      - ./config/aas-registry.yml:/workspace/config/application.yml

  sm-registry:
    image: eclipsebasyx/submodel-registry-log-mem:2.0.0-SNAPSHOT
    ports:
      - '9082:9082'
    environment:
      - SERVER_PORT=9082
    volumes:
      - ./config/sm-registry.yml:/workspace/config/application.yml       
      
  arena36-processfactory:
    image: arena36/processfactory:0.0.1-SNAPSHOT
    volumes:
      - ./config/processfactory.properties:/application/application.properties
    ports:
      - 8110:8110
    depends_on:
      aas-env:
        condition: service_healthy

  arena36-workermanager:
    image: arena36/workermanager:0.0.1-SNAPSHOT
    volumes:
      - ./config/workermanager.properties:/application/application.properties
    ports:
      - 8111:8111
    depends_on:
      aas-env:
        condition: service_healthy
